# Generated by Django 5.1.1 on 2024-09-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('postdate', models.DateField()),
                ('category', models.CharField(choices=[('business', 'ビジネス'), ('life', 'ライフ'), ('other', 'その他')], max_length=50)),
            ],
        ),
    ]
